### ISSUE TITLE
move private-transaction-families from archived to active 

### ISSUE THREAD

**Issue by ronenshemtov** [hyperledger-labs/hyperledger-labs.github.io#110]
The private-transaction-families project was archived and cannot be modified. 
We are seeing interest by the community and asking to move the file from the archived directory back to active, so that others can contribute and comment. 

Thanks,
Ronen Shem-Tov
Intel Corporate

**Comment by tkuhrt** [comment]
Can you create a PR that does this? The lab stewards can then approve it, and we can make it happen. Specifically, do a `git mv labs/archived/private-transactions-families.md labs/private-transactions-families.md`. Then `git commit -s -m "Unarchive lab"` and then all the normal stuff to push and do a PR should do it.
